version: 0.0
os: linux

files:
   - source: /index.html
     destination: /var/www/html
     

hooks:
  BeforeInstall:
     - location: aws-scripts/before-install.sh
       timeout: 300
       runas: root
  
  AfterInstall:
     - location: aws-scripts/after-install.sh
       timeout: 300
       runas: root
  
  ApplicationStart:
     - location: aws-scripts/app-start.sh
       timeout: 300
       runas: root
       
  ApplicationStop:
     - location: aws-scripts/app-stop.sh
       timeout: 300
       runas: root
